config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'users#home'
  get  'about', to: 'users#about'
  get  'signup', to: 'users#new', as: "signup"
  post 'signup', to: 'users#create', as: "create_user"
  get  'users/:id', to: 'users#show', as: "user"
  get  'users/:id/edit', to: 'users#edit', as: "edit_user"
  get  'users/:id/words', to: 'users#words', as: "user_words"
  patch  'users/:id', to: 'users#update', as: "update_user"
  delete 'users/:id', to: 'users#destroy', as: "delete_user"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'publishers', to: 'publishers#index'
  get 'publishers/:sources', to: 'publishers#show', as: "show_publisher"

  resources :user_articles, only: %i[show new create edit update destroy]

  post 'user_articles/:id', to: 'vocabs#create', as: 'create_vocab'
  delete 'user_articles', to: 'vocabs#destroy', as: 'destroy_vocab'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_articles, dependent: :destroy

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password validations: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    freturn false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update words show destroy]
  before_action :correct_user,   only: %i[edit update words show destroy]
  def home
    @today = Date.today
    news_api_key = ENV["NEWS_API_KEY_ID"]
    newsapi = News.new(news_api_key)
    all_articles = newsapi.get_everything(sources: 'bbc-news', language: 'en', page: 2)
    @all_articles = Kaminari.paginate_array(all_articles).page(params[:page]).per(8)
  end

  def new
    if logged_in?
      redirect_to root_url
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Hello #{@user.name}! Welcome to E-go!!"
      redirect_back_or root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @categories = { "経済" => 1, "エンターテイメント" => 2, "一般" => 3, "医療" => 4, "科学" => 5, "スポーツ" => 6, "技術" => 7, "その他" => 8 }
    @articles = if params[:category].present?
                  current_user.user_articles.where(category: params[:category]).page(params[:page]).per(5).order(created_at: :desc)
                else
                  current_user.user_articles.page(params[:page]).per(5).order(created_at: :desc)
                end
  end

  def category
    @category = params[:category]
    @articles = current_user.user_articles.where(category: @category).page(params[:page]).per(5).order(created_at: :desc)
  end

  def words
    @capitals1 = ("A".."N").to_a
    @capitals2 = ("O".."Z").to_a
    # n+1問題の対応
    articles = current_user.user_articles.includes(:vocabs)
    vocab_ary = []
    articles.each do |article|
      article.vocabs.each do |vocab|
        vocab_ary << vocab unless vocab_ary.map { |v| v[:english] }.include?(vocab.english)
      end
    end
    vocabs = vocab_ary.sort_by { |vocab| vocab[:english].downcase }
    if params[:capital].present?
      vocabs_capital = vocabs.select { |vocab| vocab[:english][0].include?(params[:capital].upcase) || vocab[:english][0].include?(params[:capital]) }
      @vocabs = Kaminari.paginate_array(vocabs_capital).page(params[:page]).per(20)
    else
      @vocabs = Kaminari.paginate_array(vocabs).page(params[:page]).per(20)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id]).destroy
    flash[:success] = "See you later! Hope you come back here!!"
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about.html.erb
<div class="container">
  <div class="inner ">
  	<div class="row ">
      <h1 class="">Welcome to E-go!</h1>
  	  <div class="col s12 m6 "><h4 class="blue lighten-2 white-text">E-go!</h4>
        <div class="flex-text-box">
  		    <p>E-go!は「ニュースを英語で読む」ことを<br>習慣づけるためのアプリです<br>
  		       あなたが読みたいニュースを登録して<br>英語を読む習慣を身につけましょう!!</p>
  	    </div>
      </div>
      <div class="col s12 m6 "><h4 class="blue lighten-2 white-text">Usage</h4>
        <div class="flex-text-box">
          <p> 1.気になるニュースサイトにアクセス<br>2.読みたい記事をコピー<br>3.記事を作成<br>4.翻訳したい単語をクリック </p>
        </div>
      </div>
    </div>
    <div class="row center ">
      <div class="center col s6  offset-l3">
        <% unless current_user.present?  %>
          <h3 class="pink lighten-2 white-text">Start E-go!</h3>
          <p><%= link_to "Login", signup_path, class: "btn blue lighten-2 "%><%= link_to "Signup", login_path, class: "btn blue lighten-2" %></p>
        <% end %>
        <p><%= link_to "Home", root_path, class: "btn blue lighten-2" %></p>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row flex">
    <div class="col s12 m6 center">
      <h2>Update</h2>
      <div class="row">
        <%= form_with model: @user, url:update_user_path,local: true do |f| %>
        <%= render 'shared/error_messages' %>
        <div class="row">
          <div class="input-field col s12">
            <%= f.label :name %>
            <%= f.text_field :name%>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <%= f.label :email %>
            <%= f.email_field :email %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
          <%= f.label :password %>
          <%= f.password_field :password %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation %>
          </div>
        </div>
          <% if @current_user.email != 'test@mail.com' %>
            <p><%= f.submit "Update", class: "btn btn-primary blue lighten-2 " %></p>
            <p><%= link_to "Leave this site", delete_user_path(@user), method: :delete,  data: { confirm: "退会しますか？" }, class: "btn btn  red darken-1" %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/home.html.erb
<div class="header-content">
  <h1 class="header-content-title">E-Go!</h1>
</div>
<div class="container">
<%= render partial: 'shared/link_nav_user' %>
  <h3 class="center"><%= @today %>の最新ニュース</h3>
  <div class="inner ">
    <div class="row flex">
      <% @all_articles.each do |headline| %>
      <div class="col s12 m3">
          <div class="card white hoverable">
              <a class="modal-trigger" href="#<%= headline.title %>">
                <div class="card-image">
                <% if headline.urlToImage.present? %>
                  <%=  image_tag headline.urlToImage,size:"auto" %>
                <% else %>
                  <%=  image_tag "no-image.png" ,size:"auto" %>
                <% end %>
                </div>
                <div class="card-content black-text">
                  <p><%= headline.title %></p>
                </div>
              </a>
              <div id="<%= headline.title %>" class="modal">
                <div class="modal-content">
                  <h4><%= headline.title %></h4>
                  <p><%= headline.publishedAt %></p>
                  <p><%= headline.description %></p>
                  <p><%= link_to headline.url, headline.url,class: "blue-text" , target: :_blank %></p>
                </div>
                <div class="modal-footer">
                  <p class="modal-close waves-effect waves-green btn-flat">Close</p>
                </div>
              </div>
            <div class="card-action">
            <%= link_to "記事にする", new_user_article_path(title: headline.title,url: headline.url, publishedAt: headline.publishedAt), class: " white-text btn blue lighten-2" %>
            </div>
          </div>
        </div>
      <% end %>
      </div>
  </div>
</div>
<div  class= "center-align">
  <%= paginate @all_articles %>
</div>

app/views/users/new.html.erb
<div class="container">
<div class="row flex">
  <div class="col s12 m6 center">
    <h2>Signup</h2>
    <div class="row">
      <%= form_with model: @user, url:create_user_path,local: true do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="row">
        <div class="input-field col s12">
          <%= f.label :name %>
          <%= f.text_field :name%>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.label :email %>
          <%= f.email_field :email %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
        <%= f.label :password %>
        <%= f.password_field :password %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>
        </div>
      </div>
        <%= f.submit "Create New Account", class: "btn btn-primary blue lighten-2 " %>
      <% end %>
      <%= form_with scope: :session, url:login_path, local: true do |f| %>
        <%= f.hidden_field :email, value: 'test@mail.com' %>
        <%= f.hidden_field :password, value: 'foobar' %>
        <p><%= f.submit "テストユーザーログイン", class: "btn  blue lighten-2" %></p>
      <% end %>
    </div>
  </div>

</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="inner">
    <%= render partial: 'shared/link_nav_user' %>
    <nav>
      <div class="nav-wrapper  green lighten-2">
        <ul id="nav-mobile" class="list-center hide-on-med-and-down">
          <li><%= link_to "全記事", user_path %></li>
          <% @categories.each do |key, value| %>
          <li><%= link_to key, user_path(category:value) %></li>
          <% end %>
       </ul>
      </div>
    </nav>
      <div class="row">
        <h1 class="center">マイページ</h1>
        <div class="col s12 " >
          <% @articles.each do |article| %>
            <div class="card white hoverable">
              <div class="card-content ">
                <span class="card-title ">
                  <%= article.title %>
                </span>
                <div class="content black-text">
                <p><%= article.japanese_title%></p><br>
                <p> Published at <%= article.published_at %></p>
                <p><%= link_to article.url,article.url,class: "blue-text" ,target: :_blank%></p>
                </div>
                <div class="chip green lighten-2">
                  <%= link_to article.category, user_path(category:article.category), class: "white-text"%>
                </div>
              </div>
              <div class="card-action center-align">
                <div class="option">
                  <%= link_to  "Show", user_article_path(id: article.id) ,class: 'btn blue lighten-2'%>
                  <%= link_to  "Edit", edit_user_article_path(id:article.id) ,class: 'btn green accent-3'%>
                  <%= link_to  "Delete", user_article_path(id: article.id), method: :delete, class: 'btn red darken-1', data: { confirm: "記事を削除しますか？" } %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
  </div>
  <div class="pagination center-align">
    <%= paginate @articles %>
  </div>
</div>

app/views/users/words.html.erb
<div class="container">
  <div class="inner">
    <%= render partial: 'shared/link_nav_user' %>
    <nav>
      <div class="nav-wrapper  green lighten-2 ">
        <ul id="nav-mobile" class="list-center hide-on-med-and-down">
          <% @capitals1.each do |capital| %>
            <li><%= link_to capital ,user_words_path(capital: capital.downcase) %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <nav>
      <div class="nav-wrapper  green lighten-2">
       <ul id="nav-mobile" class="list-center hide-on-med-and-down">
          <% @capitals2.each do |capital| %>
            <li><%= link_to capital ,user_words_path(capital: capital.downcase) %></li>
          <% end %>
            <li><%= link_to "All" ,user_words_path %></li>
       </ul>
      </div>
    </nav>
    <div class="row">
      <div class="your-vocabulary col s8 offset-l2">
        <h3 class="center-align">単語帳</h3>
        <table class="centered striped">
          <thead>
            <tr>
              <th>Word</th>
              <th>Meaning</th>
            </tr>
          </thead>
          <tbody>
            <% @vocabs.each do |vocab| %>
              <tr>
                <td><%= vocab.english %></td>
                <td><%= vocab.japanese %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>