config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'users#home'
  get  'about', to: 'users#about'
  get  'signup', to: 'users#new', as: "signup"
  post 'signup', to: 'users#create', as: "create_user"
  get  'users/:id', to: 'users#show', as: "user"
  get  'users/:id/edit', to: 'users#edit', as: "edit_user"
  get  'users/:id/words', to: 'users#words', as: "user_words"
  patch  'users/:id', to: 'users#update', as: "update_user"
  delete 'users/:id', to: 'users#destroy', as: "delete_user"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'publishers', to: 'publishers#index'
  get 'publishers/:sources', to: 'publishers#show', as: "show_publisher"

  resources :user_articles, only: %i[show new create edit update destroy]

  post 'user_articles/:id', to: 'vocabs#create', as: 'create_vocab'
  delete 'user_articles', to: 'vocabs#destroy', as: 'destroy_vocab'
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_link_nav.html.erb
<nav>
  <div class="nav-wrapper green lighten-2">
    <ul id="nav-mobile" class="list-center hide-on-med-and-down">
      <li><%= link_to "経済",publishers_path(category:"business")  %></li>
      <li><%= link_to "エンターテイメント",publishers_path(category:"entertainment")  %></li>
      <li><%= link_to "一般",publishers_path(category:"general")  %></li>
      <li><%= link_to "医療",publishers_path(category:"health")  %></li>
      <li><%= link_to "科学",publishers_path(category:"science")  %></li>
      <li><%= link_to "スポーツ",publishers_path(category:"sports")  %></li>
      <li><%= link_to "テクノロジー",publishers_path(category:"technology")  %></li>
    </ul>
 </div>
</nav>

app/views/shared/_link_nav_user.html.erb
<div class="col s12 m8">
  <nav>
    <div class="nav-wrapper pink lighten-2 s6">
      <ul id="nav-mobile" class="hide-on-med-and-down list-center">
          <li><%= link_to "Home",root_path %></li>
          <li><%= link_to "ニュースメディア一覧",publishers_path(category: "general") %></li>
        <% if current_user.present? %>
          <li><%= link_to "MyPage", user_path(current_user) %></li>
          <li><%= link_to "My単語一覧", user_words_path(current_user) %></li>
          <li><%= link_to "ニュースの新規登録" , new_user_article_path(current_user) %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>