config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'users#home'
  get  'about', to: 'users#about'
  get  'signup', to: 'users#new', as: "signup"
  post 'signup', to: 'users#create', as: "create_user"
  get  'users/:id', to: 'users#show', as: "user"
  get  'users/:id/edit', to: 'users#edit', as: "edit_user"
  get  'users/:id/words', to: 'users#words', as: "user_words"
  patch  'users/:id', to: 'users#update', as: "update_user"
  delete 'users/:id', to: 'users#destroy', as: "delete_user"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'publishers', to: 'publishers#index'
  get 'publishers/:sources', to: 'publishers#show', as: "show_publisher"

  resources :user_articles, only: %i[show new create edit update destroy]

  post 'user_articles/:id', to: 'vocabs#create', as: 'create_vocab'
  delete 'user_articles', to: 'vocabs#destroy', as: 'destroy_vocab'
end

app/models/publisher.rb
class Publisher < ApplicationRecord
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @category = params[:category]
    @sources = Publisher.where(category: @category).page(params[:page]).per(8)
  end

  def show
    news_api_key = ENV["NEWS_API_KEY_ID"]
    newsapi = News.new(news_api_key)
    @sources = params[:sources]
    @top_headlines = newsapi.get_top_headlines(sources: @sources)
    @today = Date.today
  end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/index.html.erb
<div class="container">
  <div class="inner ">
    <%= render partial: 'shared/link_nav_user' %>
    <%= render partial: 'shared/link_nav' %>
    <h1 class="center"><%= @category.capitalize %></h1>
    <div class="row flex">
      <% @sources.each do |source| %>
        <div class="col s12 m6">
          <div class="card white hoverable">
            <div class="card-content ">
              <span class="card-title black-text"><%= source.name %></span>
              <div class="black-text">
                <p><%= source.description %></p>
                <div class="chip green lighten-2">
                  <%= link_to source.category, publishers_path(category:source.category), class: "white-text"%>
                 </div>
                <p><%= link_to source.url, source.url, target: :_blank %></p>
              </div>
              <div class="card-action">
                <%= link_to "最新のニュース", show_publisher_path(sources: source.source_id), class: "blue-text" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="pagination center-align">
  <%= paginate @sources %>
</div>

app/views/publishers/show.html.erb
<div class="container">
  <div class="inner ">
    <%= render partial: 'shared/link_nav_user' %>
    <%= render partial: 'shared/link_nav' %>
    <h1 class="center"><%= @top_headlines[0].name %></h1>
    <h4 class="center"><%= @today %></h4>
    <div class="row flex">
      <div class="publisher">
      </div>
      <% if @top_headlines.present? %>
        <% @top_headlines.each do |headline| %>
          <div class="col s12 m3">
            <div class="card white hoverable">
              <a class="modal-trigger" href="#<%= headline.title %>">
                <div class="card-image">
                <% if headline.urlToImage.present?  %>
                  <%=  image_tag headline.urlToImage,size:"auto" %>
                <% else %>
                  <%=  image_tag "no-image.png" ,size:"auto" %>
                <% end %>
                </div>
                <div class="card-content black-text">
                  <p><%= headline.title %></p>
                </div>
              </a>
              <div id="<%= headline.title %>" class="modal">
                <div class="modal-content">
                  <h4><%= headline.title %></h4>
                  <p><%= headline.publishedAt %></p>
                  <p><%= headline.description %></p>
                  <p><%= link_to headline.url, headline.url, class: "blue-text",  target: :_blank%></p>
                </div>
                <div class="modal-footer">
                  <p class="modal-close waves-effect waves-green btn-flat">Close</p>
                </div>
              </div>
            <div class="card-action">
              <%= link_to "記事にする", new_user_article_path(title: headline.title,url: headline.url, publishedAt: headline.publishedAt),class: "white-text btn blue lighten-2"  %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>Headline news doesn't exist here</p>
    <% end %>
    </div>
  </div>
</div>