config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'users#home'
  get  'about', to: 'users#about'
  get  'signup', to: 'users#new', as: "signup"
  post 'signup', to: 'users#create', as: "create_user"
  get  'users/:id', to: 'users#show', as: "user"
  get  'users/:id/edit', to: 'users#edit', as: "edit_user"
  get  'users/:id/words', to: 'users#words', as: "user_words"
  patch  'users/:id', to: 'users#update', as: "update_user"
  delete 'users/:id', to: 'users#destroy', as: "delete_user"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'publishers', to: 'publishers#index'
  get 'publishers/:sources', to: 'publishers#show', as: "show_publisher"

  resources :user_articles, only: %i[show new create edit update destroy]

  post 'user_articles/:id', to: 'vocabs#create', as: 'create_vocab'
  delete 'user_articles', to: 'vocabs#destroy', as: 'destroy_vocab'
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
    © 2019 E-go!
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav>
    <div class="nav-wrapper">
      <%= link_to "E-go!", root_path, class: 'brand-logo' %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if logged_in? %>
        <li><%= @current_user.email %></li>
        <li><%= link_to "About", about_path %> </li>
        <li ><%= link_to "Logout", logout_path, method: :delete %></li>
        <li ><%= link_to "Settings", edit_user_path(current_user) %></li>
      </ul>
      <% else %>
        <li><%= link_to "About", about_path %> </li>
        <li><%= link_to "Signup", signup_path %></li>
        <li><%= link_to "Login", login_path %></li>
      <% end %>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-Go</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>